---

dist: bionic

language: python
python:
  - 3.6
services: docker

env:
  global:
    - ROLE_NAME: shell
  matrix:
    - MOLECULE_DISTRO: ubuntu/xenial
    - MOLECULE_DISTRO: ubuntu/bionic
    - MOLECULE_DISTRO: ubuntu/cosmic
    - MOLECULE_DISTRO: ubuntu/disco
    - MOLECULE_DISTRO: centos/7
    - MOLECULE_DISTRO: debian/jessie
    - MOLECULE_DISTRO: debian/buster
    - MOLECULE_DISTRO: fedora/29

install:
  - curl --proto '=https' -sS https://gist.githubusercontent.com/Teebor-Choka/0d72636444f560cc5d287ae1387fb9ce/raw/ | sh
  - pip3 install molecule

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
