---

- name: establish .bashrc.d directory
  file:
    path: "{{ bashrc_d_dir }}"
    owner: "{{ ansible_user }}"
    mode: "u=rwx,go="
    state: directory

- block:
  - name: find existing bashrc.d contents
    find:
      path: "{{ bashrc_d_dir }}"
      pattern: "*.bashrc" 
    register: existing_bashrc_files

  - name: remove existing bashrc.d contents
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ existing_bashrc_files.files }}"
  when:
    - general['file_behavior'] == 'replace'

- name: establish .bashrc file
  template:
    src: .bashrc
    dest: ~/.bashrc
    owner: "{{ ansible_user }}"
    mode: "u=rwX,go="

- name: establish bashrc.d components
  template:
    src: "{{ item }}"
    dest: "{{ bashrc_d_dir }}/{{ (item | basename | splitext)[0] }}.bashrc"
    owner: "{{ ansible_user }}"
    mode: "u=rwX,go="
  with_fileglob:
    - ../templates/bashrc.d/*.bashrc
    - ../templates/rc.d/*.rc
