---

- name: bash | establish
  become: "{{ (ansible_system == 'Linux') | bool }}"
  package:
    name:
      - bash
      - bash-completion
    state: present
  tags: install

- name: bash | .bashrc file
  become: false
  when: shell_bash_rc is defined
  copy:
    content: "{{ shell_bash_rc }}"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: "u=rwx,go="
  tags: configure
