---

- name: establish depenencies
  become: true
  package:
    name:
      - bash
      - bash-completion
    state: present
  tags: install

- name: establish .bashrc.d directory
  become: false
  file:
    path: "{{ bashrc_d_dir }}"
    mode: "u=rwx,go="
    state: directory
  tags: configure

- name: establish .bashrc file
  become: false
  template:
    src: .bashrc.j2
    dest: ~/.bashrc
    mode: "u=rwX,go="
  tags: configure

- name: establish bashrc.d components
  become: false
  template:
    src: "{{ item }}"
    dest: "{{ bashrc_d_dir }}/\
      {{ (item | regex_replace('\\.j2','') | basename | splitext)[0] }}.bashrc"
    mode: "u=rwX,go="
  with_fileglob:
    - "{{ role_path }}/templates/bashrc.d/*.bashrc.j2"
    - "{{ role_path }}/templates/rc.d/*.rc.j2"
  tags: configure
