---

- name: prepare facts
  set_fact:
    shell_bash:
      rc_d_dir: "{{ ('rc_d_dir' in shell_bash) | ternary(shell_bash['rc_d_dir'], ansible_env.HOME + '/.bashrc.d/') }}"

- name: establish depenencies
  become: true
  package:
    name:
      - bash
      - bash-completion
    state: present
  tags: install

- name: establish rc.d directory
  become: false
  file:
    path: "{{ shell_bash['rc_d_dir'] }}"
    mode: "u=rwx,go="
    state: directory
  tags: configure

- name: establish .bashrc file
  become: false
  template:
    src: .bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: "u=rwX,go="
    follow: true
  tags: configure

- name: establish rc.d components
  become: false
  template:
    src: "{{ item }}"
    dest: "{{ shell_bash['rc_d_dir'] }}/\
      {{ (item | regex_replace('\\.j2','') | basename | splitext)[0] }}.bashrc"
    mode: "u=rwX,go="
    follow: true
  with_fileglob:
    - "{{ role_path }}/templates/bashrc.d/*.bashrc.j2"
    - "{{ role_path }}/templates/rc.d/*.rc.j2"
  tags: configure
