---

- when: bash is defined
  import_tasks: bash.yml

- name: introduce custom inputrc configuration
  when: inputrc is defined
  become: false
  template:
    src: .inputrc.j2
    dest: "~/.inputrc"
    mode: "ug=rwX,o="
