---

- when: shell_bash is defined
  include_tasks: bash.yml

- when: shell_zsh is defined
  include_tasks: zsh.yml

- name: set default shell
  when: shell_default is defined
  command: chsh -s $(which {{ shell_default }})

- name: introduce custom inputrc configuration
  when: shell_inputrc is defined
  become: false
  template:
    src: .inputrc.j2
    dest: "~/.inputrc"
    mode: "ug=rwX,o="
    follow: true
