---

- when: shell_bash is defined
  include_tasks: bash.yml

- name: introduce custom inputrc configuration
  when: shell_inputrc is defined
  become: false
  template:
    src: .inputrc.j2
    dest: "~/.inputrc"
    mode: "ug=rwX,o="
    follow: true
