---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repository
      when: "ansible_pkg_mgr == 'apt'"
      apt:
        update_cache: true
  roles:
    - role: ansible-role-shell
      vars:
        shell_inputrc:
          - "set completion-ignore-case On"
        shell_default: zsh
        shell_zsh_install: true
        shell_zsh_oh_my_zsh: true
        shell_bash_install: true
        shell_bash_rc: |
          #!/usr/bin/env bash
          with_trace() {
              if [ -n "$1" ] ; then
                  local original_xtrace_setting
                  original_xtrace_setting="$(shopt -po xtrace)"

                  set -x
                  $1
                  { STATUS=$?; eval "$original_xtrace_setting"; } 2>/dev/null

                  return $STATUS
              else
                  echo "usage: with_trace '<command>'"
              fi
          }
