---

- name: Converge
  hosts: all
  pre_tasks:
    - name: update apt repository
      when: "ansible_pkg_mgr == 'apt'"
      apt:
        update_cache: true
  roles:
    - role: ansible-role-shell
      vars:
        shell_use_color: false
        shell_inputrc:
          - "set completion-ignore-case On"
        shell_default: zsh
        shell_zsh: {}
        shell_zsh_oh_my_zsh: true
        shell_bash:
          rc_d_dir: "~/.bashrc.d/"
          history:
            size: 1500
          shopt:
            histappend: true
          set:
            history: true
          alias:
            mkdir: 'mkdir -p'
          functions:
            - |
              with_trace() {
                  if [ -n "$1" ] ; then
                      local original_xtrace_setting
                      original_xtrace_setting="$(shopt -po xtrace)"

                      set -x
                      $1
                      { STATUS=$?; eval "$original_xtrace_setting"; } 2>/dev/null

                      return $STATUS
                  else
                      echo "usage: with_trace '<command>'"
                  fi
              }

  post_tasks:
    - name: bashrc.d directory should be present
      block:
        - name: check file presence
          stat:
            path: "{{ ansible_env.HOME }}/.bashrc.d/"
          register: r
        - name: evaluate file presence
          assert:
            that:
              - r.stat.isdir is defined
              - r.stat.isdir
            fail_msg: bashrc.d directory should be present
