---

dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: instance
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: ${MOLECULE_DISTRO:-ubuntu/bionic}/amd64
    architecture: x86_64
    config:
      limits.cpu: "2"
    devices:
      kvm:
        path: /dev/kvm
        type: unix-char
    profiles:
      - default
    force_stop: false
    wait_for_ipv4_addresses: true
    timeout: 60
provisioner:
  name: ansible
  log: true
  options:
    v: false
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
verifier:
  name: testinfra
  lint:
    name: flake8
